const sd = () => {
    return [
        {
            "id": 1,
            "name": "Badminton - Men's Singles",
            "tag": "Badminton-MS",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-MS.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Ram Yerra", "spoc_contact": "9346103493" }, { "spoc_name": "Yathin kumar", "spoc_contact": "7998671111" }, { "spoc_name": "Risshi Sunku", "spoc_contact": "9381686735" }, { "spoc_name": "Ajay Chhajed", "spoc_contact": "7300049086" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 2,
            "name": "Badminton - Men's Doubles",
            "tag": "Badminton-MD",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-MD.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Ram Yerra", "spoc_contact": "9346103493" }, { "spoc_name": "Yathin kumar", "spoc_contact": "7998671111" }, { "spoc_name": "Risshi Sunku", "spoc_contact": "9381686735" }, { "spoc_name": "Ajay Chhajed", "spoc_contact": "7300049086" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 3,
            "name": "Badminton - Women's Singles",
            "tag": "Badminton-WS",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-WS.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Ram Yerra", "spoc_contact": "9346103493" }, { "spoc_name": "Yathin kumar", "spoc_contact": "7998671111" }, { "spoc_name": "Risshi Sunku", "spoc_contact": "9381686735" }, { "spoc_name": "Ajay Chhajed", "spoc_contact": "7300049086" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 4,
            "name": "Badminton - Women's Singles",
            "tag": "Badminton-WD",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-WD.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Ram Yerra", "spoc_contact": "9346103493" }, { "spoc_name": "Yathin kumar", "spoc_contact": "7998671111" }, { "spoc_name": "Risshi Sunku", "spoc_contact": "9381686735" }, { "spoc_name": "Ajay Chhajed", "spoc_contact": "7300049086" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 2, "max_female": 2 }
        },
        {
            "id": 5,
            "name": "Badminton - Mixed Doubles",
            "tag": "Badminton-MiD",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-MiD.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Ram Yerra", "spoc_contact": "9346103493" }, { "spoc_name": "Yathin kumar", "spoc_contact": "7998671111" }, { "spoc_name": "Risshi Sunku", "spoc_contact": "9381686735" }, { "spoc_name": "Ajay Chhajed", "spoc_contact": "7300049086" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 6,
            "name": "Table Tennis - Men's Singles",
            "tag": "TableTennis-MS",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-MS.gif",
            "rules": "/rules/TableTennis-S.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay", "spoc_contact": "9011496298" }, { "spoc_name": "Krushikar", "spoc_contact": "6366028143" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 7,
            "name": "Table Tennis - Men's Doubles",
            "tag": "TableTennis-MD",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-MD.gif",
            "rules": "/rules/TableTennis-D.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay", "spoc_contact": "9011496298" }, { "spoc_name": "Krushikar", "spoc_contact": "6366028143" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 8,
            "name": "Table Tennis - Women's Singles",
            "tag": "TableTennis-WS",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-WS.gif",
            "rules": "/rules/TableTennis-S.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay", "spoc_contact": "9011496298" }, { "spoc_name": "Krushikar", "spoc_contact": "6366028143" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 9,
            "name": "Table Tennis - Women's Doubles",
            "tag": "TableTennis-WD",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-WD.jpeg",
            "rules": "/rules/TableTennis-D.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay", "spoc_contact": "9011496298" }, { "spoc_name": "Krushikar", "spoc_contact": "6366028143" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 2, "max_female": 2 }
        },
        {
            "id": 10,
            "name": "Table Tennis - Mixed Doubles",
            "tag": "TableTennis-MiD",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-MiD.avif",
            "rules": "/rules/TableTennis-D.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay", "spoc_contact": "9011496298" }, { "spoc_name": "Krushikar", "spoc_contact": "6366028143" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 11,
            "name": "Throwball",
            "tag": "Throwball",
            "type": "major",
            "icon": "/sportsicons/Volleyball.png",
            "displayImage": "/sportsdisplay/Throwball.gif",
            "rules": "/rules/Throwball.txt ",
            "rulesURL": "../../rulespdf/Throwball.pdf",
            "spoc": [{ "spoc_name": "Avantika", "spoc_contact": "8179640318" }, { "spoc_name": "Rachna", "spoc_contact": "9113983604" }],
            "requirements": { "min_players": 7, "max_players": 9, "min_female": 2, "max_female": 9 }
        },
        {
            "id": 12,
            "name": "Football",
            "tag": "Football",
            "type": "major",
            "icon": "/sportsicons/Football.png",
            "displayImage": "/sportsdisplay/Football.gif",
            "rules": "/rules/Football.txt ",
            "rulesURL": "../../rulespdf/Football.pdf",
            "spoc": [{ "spoc_name": "Jainav", "spoc_contact": "7014006445" }, { "spoc_name": "Yash", "spoc_contact": "7046361449" }, { "spoc_name": "Yugaan", "spoc_contact": "6366055993" }],
            "requirements": { "min_players": 6, "max_players": 9, "min_female": 0, "max_female": 9 }
        },
        {
            "id": 13,
            "name": "Cricket",
            "tag": "Cricket",
            "type": "major",
            "icon": "/sportsicons/Cricket.png",
            "displayImage": "/sportsdisplay/Cricket.gif",
            "rules": "/rules/Cricket.txt ",
            "rulesURL": "../../rulespdf/Cricket.pdf",
            "spoc": [{ "spoc_name": "Ritik Bansal", "spoc_contact": "9777297550" }, { "spoc_name": "Vishal rao", "spoc_contact": "8349850988" }, { "spoc_name": "Prabal", "spoc_contact": "9622377645" }, { "spoc_name": "Aditya Kaka", "spoc_contact": "9900149539" }],
            "requirements": { "min_players": 10, "max_players": 12, "min_female": 0, "max_female": 12 }
        },
        {
            "id": 14,
            "name": "Volleyball",
            "tag": "Volleyball",
            "type": "major",
            "icon": "/sportsicons/Volleyball.png",
            "displayImage": "/sportsdisplay/Volleyball.gif",
            "rules": "/rules/Volleyball.txt ",
            "rulesURL": "../../rulespdf/Volleyball.pdf",
            "spoc": [{ "spoc_name": "Ganesh", "spoc_contact": "7286833180" }, { "spoc_name": "Harsha", "spoc_contact": "6300238239" }, { "spoc_name": "Manan", "spoc_contact": "9328949833" }],
            "requirements": { "min_players": 7, "max_players": 9, "min_female": 0, "max_female": 9 }
        },
        {
            "id": 15,
            "name": "Basketball",
            "tag": "Basketball",
            "type": "major",
            "icon": "/sportsicons/Basketball.png",
            "displayImage": "/sportsdisplay/Basketball.gif",
            "rules": "/rules/Basketball.txt ",
            "rulesURL": "../../rulespdf/Basketball.pdf",
            "spoc": [{ "spoc_name": "Ayush Sawlani", "spoc_contact": "6263666763" }, { "spoc_name": "Rohit", "spoc_contact": "8168090470" }],
            "requirements": { "min_players": 5, "max_players": 8, "min_female": 0, "max_female": 8 }
        },
        {
            "id": 16,
            "name": "Basketball Men 3v3",
            "tag": "Basketball-M3",
            "type": "major",
            "icon": "/sportsicons/Basketball.png",
            "displayImage": "/sportsdisplay/Basketball-M3.gif",
            "rules": "/rules/Basketball-3.txt ",
            "rulesURL": "../../rulespdf/Basketball.pdf",
            "spoc": [{ "spoc_name": "Ayush Sawlani", "spoc_contact": "6263666763" }, { "spoc_name": "Rohith (MS)", "spoc_contact": "8168090470" }],
            "requirements": { "min_players": 3, "max_players": 4, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 17,
            "name": "Basketball Women",
            "tag": "Basketball-W",
            "type": "major",
            "icon": "/sportsicons/Basketball.png",
            "displayImage": "/sportsdisplay/Basketball-W.gif",
            "rules": "/rules/Basketball-3.txt ",
            "rulesURL": "../../rulespdf/Basketball.pdf",
            "spoc": [{ "spoc_name": "Ayush Sawlani", "spoc_contact": "6263666763" }, { "spoc_name": "Rohith (MS)", "spoc_contact": "8168090470" }],
            "requirements": { "min_players": 3, "max_players": 4, "min_female": 3, "max_female": 4 }
        },
        {
            "id": 18,
            "name": "Valorant",
            "tag": "Valorant",
            "type": "minor",
            "icon": "/sportsicons/Valorant.png",
            "displayImage": "/sportsdisplay/Valorant.gif",
            "rules": "/rules/Valorant.txt ",
            "rulesURL": "../../rulespdf/Valorant.pdf",
            "spoc": [{ "spoc_name": "Srinivas Manda", "spoc_contact": "9110322406" }, { "spoc_name": "Saket Gurjar", "spoc_contact": "8502883397" }],
            "requirements": { "min_players": 5, "max_players": 5, "min_female": 0, "max_female": 5 }
        },
        {
            "id": 19,
            "name": "CodM",
            "tag": "CodM",
            "type": "minor",
            "icon": "/sportsicons/CodM.png",
            "displayImage": "/sportsdisplay/CodM.gif",
            "rules": "/rules/CoDM.txt ",
            "rulesURL": "../../rulespdf/CoDM.pdf",
            "spoc": [{ "spoc_name": "Prashant", "spoc_contact": "7989839700" },{ "spoc_name": "Sreenivas", "spoc_contact": "8919255206" }],
            "requirements": { "min_players": 5, "max_players": 5, "min_female": 0, "max_female": 5 }
        },
        {
            "id": 20,
            "name": "Fifa Singles",
            "tag": "Fifa-S",
            "type": "minor",
            "icon": "/sportsicons/Fifa.png",
            "displayImage": "/sportsdisplay/Fifa.gif",
            "rules": "/rules/Fifa.txt ",
            "rulesURL": "../../rulespdf/Fifa.pdf",
            "spoc": [{ "spoc_name": "Abhinav", "spoc_contact": "8296683415" }, { "spoc_name": "Shridhar", "spoc_contact": "8000877380" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 21,
            "name": "Fifa Doubles",
            "tag": "Fifa-D",
            "type": "minor",
            "icon": "/sportsicons/Fifa.png",
            "displayImage": "/sportsdisplay/Fifa-D.gif",
            "rules": "/rules/Fifa.txt ",
            "rulesURL": "../../rulespdf/Fifa.pdf",
            "spoc": [{ "spoc_name": "Abhinav", "spoc_contact": "8296683415" }, { "spoc_name": "Sridhar", "spoc_contact": "8000877380" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 2 }
        },
        {
            "id": 22,
            "name": "Gully Cricket",
            "tag": "GullyCricket",
            "type": "minor",
            "icon": "/sportsicons/Cricket.png",
            "displayImage": "/sportsdisplay/GullyCricket.gif",
            "rules": "/rules/GullyCricket.txt ",
            "rulesURL": "../../rulespdf/GullyCricket.pdf",
            "spoc": [{ "spoc_name": "Vamshi G", "spoc_contact": "9182492165" }, { "spoc_name": "Niteesh", "spoc_contact": "7337080666" }],
            "requirements": { "min_players": 5, "max_players": 5, "min_female": 1, "max_female": 5 }
        },
        {
            "id": 23,
            "name": "Foosball",
            "tag": "Foosball",
            "type": "minor",
            "icon": "/sportsicons/Foosball.png",
            "displayImage": "/sportsdisplay/Foosball.gif",
            "rules": "/rules/Foosball.txt ",
            "rulesURL": "../../rulespdf/Foosball.pdf",
            "spoc": [{ "spoc_name": "Vamshidhar (2021)", "spoc_contact": "8501824685" }, { "spoc_name": "Shashank", "spoc_contact": "9823927821" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 2 }
        },
        {
            "id": 24,
            "name": "Chess",
            "tag": "Chess",
            "type": "minor",
            "icon": "/sportsicons/Chess.png",
            "displayImage": "/sportsdisplay/Chess.gif",
            "rules": "/rules/Chess.txt ",
            "rulesURL": "../../rulespdf/Chess.pdf",
            "spoc": [{ "spoc_name": "Rishi", "spoc_contact": "7981569233" }, { "spoc_name": "Teja", "spoc_contact": "9849833385" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 25,
            "name": "Gym Men",
            "tag": "Gym",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Gym.gif",
            "rules": "/rules/Gym.txt ",
            "rulesURL": "../../rulespdf/Gym.pdf",
            "spoc": [{ "spoc_name": "Nitin Pandey", "spoc_contact": "9810466897" },
            { "spoc_name": "Adwait", "spoc_contact": "7000420361" },
            { "spoc_name": "Vidhu Arora", "spoc_contact": "9501969884" },
            { "spoc_name": "Karan Raj Pandey", "spoc_contact": "9305608725" },
            { "spoc_name": "Ayush Singh", "spoc_contact": "9407341153" },
            { "spoc_name": "Puneet Kalyan", "spoc_contact": "8618132698" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 26,
            "name": "Gym Women",
            "tag": "Gym-W",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Gym-W.gif",
            "rules": "/rules/Gym.txt ",
            "rulesURL": "../../rulespdf/Gym.pdf",
            "spoc": [{ "spoc_name": "Nitin Pandey", "spoc_contact": "9810466897" },
            { "spoc_name": "Adwait", "spoc_contact": "7000420361" },
            { "spoc_name": "Vidhu Arora", "spoc_contact": "9501969884" },
            { "spoc_name": "Karan Raj Pandey", "spoc_contact": "9305608725" },
            { "spoc_name": "Ayush Singh", "spoc_contact": "9407341153" },
            { "spoc_name": "Puneet Kalyan", "spoc_contact": "8618132698" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 27,
            "name": "Carroms",
            "tag": "Carroms",
            "type": "minor",
            "icon": "/sportsicons/Carroms.png",
            "displayImage": "/sportsdisplay/Carroms.gif",
            "rules": "/rules/Carroms.txt ",
            "rulesURL": "../../rulespdf/Carroms.pdf",
            "spoc": [{ "spoc_name": "keerthan", "spoc_contact": "6281845781" }, { "spoc_name": "sougandh", "spoc_contact": "9946569704" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 2 }
        },
        {
            "id": 28,
            "name": "Tug Of War Men",
            "tag": "TugOfWar",
            "type": "minor",
            "icon": "/sportsicons/TugOfWar.png",
            "displayImage": "/sportsdisplay/TugOfWar.gif",
            "rules": "/rules/TugOfWar.txt ",
            "rulesURL": "../../rulespdf/TugOfWar.pdf",
            "spoc": [{ "spoc_name": "Arya Kondawar", "spoc_contact": "6300841030" }, { "spoc_name": "Mukul", "spoc_contact": "9728669749" }],
            "requirements": { "min_players": 8, "max_players": 10, "min_female": 0, "max_female": 10 }
        },
        {
            "id": 29,
            "name": "Tug Of War Women",
            "tag": "TugOfWar-W",
            "type": "minor",
            "icon": "/sportsicons/TugOfWar.png",
            "displayImage": "/sportsdisplay/TugOfWar-W.gif",
            "rules": "/rules/TugOfWar.txt ",
            "rulesURL": "../../rulespdf/TugOfWar.pdf",
            "spoc": [{ "spoc_name": "Arya Kondavar", "spoc_contact": "6300841030" }, { "spoc_name": "Yash", "spoc_contact": "9109999159" }],
            "requirements": { "min_players": 8, "max_players": 10, "min_female": 8, "max_female": 10 }
        },
        {
            "id": 30,
            "name": "Tennis Singles",
            "tag": "Tennis-MS",
            "type": "major",
            "icon": "/sportsicons/Tennis.png",
            "displayImage": "/sportsdisplay/Tennis.gif",
            "rules": "/rules/Tennis.txt ",
            "rulesURL": "../../rulespdf/Tennis.pdf",
            "spoc": [{ "spoc_name": "Chaitanya", "spoc_contact": "8105715824" }, { "spoc_name": "Agastya", "spoc_contact": "7760540123" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 31,
            "name": "Tennis Doubles",
            "tag": "Tennis-MD",
            "type": "major",
            "icon": "/sportsicons/Tennis.png",
            "displayImage": "/sportsdisplay/Tennis-D.gif",
            "rules": "/rules/Tennis.txt ",
            "rulesURL": "../../rulespdf/Tennis.pdf",
            "spoc": [{ "spoc_name": "Chaitanya", "spoc_contact": "8105715824" }, { "spoc_name": "Agastya", "spoc_contact": "7760540123" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 0 }
        }
    ]
}

export default sd;